---
title: "607 Assignment 2"
author: "Jiho Kim"
date: "9/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#SQL code to create database
```{Postgresql}
Create Table movie (film_id SERIAL PRIMARY KEY NOT NULL, 
					title VARCHAR(255) NOT NULL UNIQUE)
;

Create Table rater (rater_id SERIAL PRIMARY KEY NOT NULL,
				   rater_name VARCHAR (255) NOT NULL UNIQUE)
;

Create Table rating (films_id SERIAl  NOT NULL,
					rater_id INT NOT NULL,
					rating INT NULL)
;

INSERT INTO movie(title)
VALUES ('Black Widow'),('Cruella'),('Jungle Cruise'),('The Suicide Squad'),('Shang Chi'),('Candy Man')
;

INSERT INTO rater(rater_name)
VALUES ('Dad'),('Jason'),('Joseph'),('Brother'),('Abby'),('Steve')
;

INSERT INTO rating(films_id,rater_id, rating)
VALUES(1,1,4),(1,2,NULL),(1,3,NULL),(1,4,3),(1,5,4),(1,6,NULL),(2,1,4),(2,2,4),(2,3,2),(2,4,2),
(2,5,4),(2,6,4),(3,1,5),(3,2,3),(3,3,NULL),(3,4,2),(3,5,5),(3,6,3),(4,1,4),(4,2,NULL),(4,3,NULL),
(4,4,2),(4,5,5),(4,6,4),(5,1,3),(5,2,3),(5,3,2),(5,4,2),(5,5,3),(5,6,3),(6,1,4),(6,2,4),(6,3,2),(6,4,3),
(6,5,4),(6,6,NULL)
;
```

#connect PostgreSQL to R
```{r installing}

library(RPostgres)
library(DBI)
library(ggplot2)

moviedb <- dbConnect(drv = Postgres(), dbname = 'hw2', host='localhost', port=5432, user = 'postgres', password = 'wlgh7184')
```

```{r }
dbListTables(moviedb)
```

```{r tables}
r.movie <- dbReadTable(moviedb, 'movie')
r.rater <- dbReadTable(moviedb, 'rater')
r.rating <- dbReadTable(moviedb, 'rating')
```

#Handling missing Data
```{r missing data}
new.rating <- na.omit(r.rating)
```

#Quality graphic
``` {r bargraph}
movie <- 1:6
avg <- c(11/3,20/6,18/5,15/4,16/6,17/5)

average <- as.table(setNames(avg,movie))
barplot(average, ylim=c(0,5),main = "Average Movie Rating", names.arg = c('1','2','3','4','5','6'))
```

#Analysis
Based on the barplot, Suicide Squad(Id#4) had the highest average moving rating and Shang Chi had the lowest average rating. If were to recommend the movies to this sample of people, I would recommend movies involving supervillain. 